### ISSUE TITLE
configure:3403: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by lordB8r** [coapp-packages/libiconv#1]
On OSX 10.8, with xcode5-dp3 Installed. used brew to install libxml2 and libxslt, don't have mac ports, installed libiconv-1.14, and have folder for libiconv-1.13.1, but each time i try to run the ./configure --path=/usr/local/Cellar/libiconv/1.13.1, i get this error.

Check the log and it just repeats the same information.

**Comment by madewokherd** [comment]
This has nothing to do with us. We are not authors of libiconv. We just package it for Windows (specifically nuget).
